src/AppBundle/Entity/Language/Language.php
<?php

namespace AppBundle\Entity\Language;

use AppBundle\Entity\Identifiable;

class Language extends Identifiable
{
    const EN = 'en';
    const UK = 'uk';
    const RU = 'ru';

    /** @var string */
    private $code;
    /** @var bool */
    private $isActive;

    /**
     * @param int $id
     * @param string $code
     * @param bool $isActive
     */
    public function __construct($id, $code, $isActive)
    {
        parent::__construct($id);
        $this->code = $code;
        $this->isActive = $isActive;
    }

    /**
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * @return bool
     */
    public function isActive()
    {
        return $this->isActive;
    }
}

src/AppBundle/Resources/views/list/item.html.twig
<div class="item">
    <a href="{{ item.url }}" {% if nofollow %} rel="nofollow" {% endif %}>
        <div class="item_content">
            <table>
                <tr>
                    <td>
                        {{ item.text }}
                        {% if item.additional is not empty %}
                            <span class="additional">
                                ({{ item.additional }})
                            </span>
                        {% endif %}
                    </td>
                </tr>
            </table>
        </div>
    </a>
</div>

src/AppBundle/Resources/views/list/items.html.twig
{% for item in items %}
    {% include '@App/list/item.html.twig' with {
        item: item,
        nofollow: nofollow
    } %}
{% endfor %}

src/AppBundle/Resources/views/list/list.html.twig
<div
    class="
        list
        {% if list.active %} active {% else %} inactive {% endif %}
        loadable
    "
    data-upload-url-prefix="{{ list.uploadUrlPrefix }}"
>
    <h1 class="items_header">
        <a
            {#href="{{ url(path, {#}
                {#_locale: _locale,#}
                {#is_desktop_version: is_desktop_version#}
            {#}) }}"#}
            {#onclick="switch_to_list($(this).parent().parent())"#}
        >
            {{ list.header }}
            <div
                class="item_corner"
                style="border-color:{{ random_color() }};"
            ></div>
        </a>
    </h1>
    <div class="items">
        {% include '@App/list/items.html.twig' with {
            items: list.items,
            nofollow: list.nofollow
        } %}
        <div class="af"></div>
    </div>
</div>

src/AppBundle/Resources/views/list/pagination.html.twig
{#require: page#}

<div class="pages">
    <div>
        {% for pagination_page in page.pages %}
            {% if not pagination_page.active %}
                <a
                        class="page"
                        href="{{ url('parallango2', {
                            parallangoId: pagination_page.parallango.id,
                            pageNumber: pagination_page.number + 1
                        }) }}"
                        data-is-next="{{ pagination_page.isNext }}">
                    {{ pagination_page.text|raw }}
                </a>
            {% else %}
                <div class="page_on">{{ pagination_page.text }}</div>
            {% endif %}
        {% endfor %}
    </div>
</div>
<div class="af"></div>

src/AppBundle/Resources/views/list/parallango.html.twig
{#require: parallango, language, nofollow#}

{% include "@App/list/item.html.twig" with {
    href: "/book/" ~ parallango.id,
    text: parallango.title(language),
    additional: parallango.author.name(language),
    nofollow: nofollow
} %}

src/AppBundle/Resources/views/list/section.html.twig
{#require: section, language, nofollow#}

{% include "@App/list/item.html.twig" with {
    href: "/section/" ~ section.id,
    text: section.title(language),
    additional: section.nrBooks,
    nofollow: nofollow
} %}